services:
    mnr-laravel:
        extends:
            file: docker-compose-common.yml
            service: laravel
        ports:
            - "8012:80"
        restart: unless-stopped
        depends_on:
            - mysql
            - redis

    # node:
    #     extends:
    #         file: docker-compose-common.yml
    #         service: node
    #     # command: npm run dev -- --host
    #     command: tail -f /dev/null

    mysql:
        extends:
            file: docker-compose-common.yml
            service: mysql

    redis:
        extends:
            file: docker-compose-common.yml
            service: redis

    phpmyadmin:
        extends:
            file: docker-compose-common.yml
            service: phpmyadmin
        ports:
            - "8092:80"

networks:
    mnr-network:
volumes:
    mnr-mysql:
        driver: local
    mnr-redis:
        driver: local
